name: Release Charts

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    # depending on default permission settings for your org (contents being read-only or read-write for workloads), you will have to add permissions
    # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Bump chart version
        if: github.actor != 'github-actions[bot]'
        env:
          FILE: charts/wazuh/Chart.yaml
        run: |
          current=$(grep '^version:' "$FILE" | awk '{print $2}')
          IFS='.' read -r major minor patch <<< "$current"
          patch=$((patch + 1))
          new_version="$major.$minor.$patch"
          sed -i "s/^version:.*/version: $new_version/" "$FILE"
          sed -i "s/Version-$current/Version-$new_version/" README.md charts/wazuh/README.md
          git add "$FILE" README.md charts/wazuh/README.md
          git commit -m "ci: bump chart version to $new_version"
          git push
      
      
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        with:
          config: cr.yaml
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
